//auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

//locks
export const FIND_LOCK = 'FIND_LOCK';
export const UPDATE_LOCKS = 'UPDATE_LOCKS';
// export const CLEAR_LOCKS = 'CLEAR_LOCKS';

export const UPDATE_CRITERIA = 'UPDATE_CRITERIA';

export const GET_MAX_SERIAL_NUM_PENDING = 'GET_MAX_SERIAL_NUM_PENDING';
export const GET_MAX_SERIAL_NUM_SUCCESS = 'GET_MAX_SERIAL_NUM_SUCCESS';
export const GET_MAX_SERIAL_NUM_FAILED = 'GET_MAX_SERIAL_NUM_FAILED';

export const SET_INDEX = 'SET_INDEX';
export const SET_ENABLED = 'SET_ENABLED';
export const SET_THRESHOLD = 'SET_THRESHOLD';

//test
const stateEnum = {
  NOT_STARTED: 0,
  PENDING: 1,
  SUCCESS: 2,
  FAILED: 3,
};
export const { NOT_STARTED, PENDING, SUCCESS, FAILED } = stateEnum;

export const TEST_REQUEST = 'TEST_REQUEST';
export const TEST_SUCCESS = 'TEST_SUCCESS';
// export const TEST_FAILED = 'TEST_FAILED';

export const SCAN_BROADCAST = 'SCAN_BROADCAST';

export const TEST_BROADCAST_INFO_PENDING = 'TEST_BROADCAST_INFO_PENDING';
export const TEST_BROADCAST_INFO_SUCCESS = 'TEST_BROADCAST_INFO_SUCCESS';
export const TEST_BROADCAST_INFO_FAILED = 'TEST_BROADCAST_INFO_FAILED';

export const INIT_LOCK_PENDING = 'INIT_LOCK_PENDING';
export const INIT_LOCK_SUCCESS = 'INIT_LOCK_SUCCESS';
export const INIT_LOCK_FAILED = 'INIT_LOCK_FAILED';

export const TEST_RTC_PENDING = 'TEST_RTC_PENDING';
export const TEST_RTC_SUCCESS = 'TEST_RTC_SUCCESS';
export const TEST_RTC_FAILED = 'TEST_RTC_FAILED';

export const TEST_HALL_PENDING = 'TEST_HALL_PENDING';
export const TEST_HALL_SUCCESS = 'TEST_HALL_SUCCESS';
export const TEST_HALL_FAILED = 'TEST_HALL_FAILED';

export const TEST_DOOR_SENSOR_PENDING = 'TEST_DOOR_SENSOR_PENDING';
export const TEST_DOOR_SENSOR_SUCCESS = 'TEST_DOOR_SENSOR_SUCCESS';
export const TEST_DOOR_SENSOR_FAILED = 'TEST_DOOR_SENSOR_FAILED';

export const TEST_TOUCH_KEY_PENDING = 'TEST_TOUCH_KEY_PENDING';
export const TEST_TOUCH_KEY_SUCCESS = 'TEST_TOUCH_KEY_SUCCESS';
export const TEST_TOUCH_KEY_FAILED = 'TEST_TOUCH_KEY_FAILED';

export const TEST_NFC_CHIP_PENDING = 'TEST_NFC_CHIP_PENDING';
export const TEST_NFC_CHIP_SUCCESS = 'TEST_NFC_CHIP_SUCCESS';
export const TEST_NFC_CHIP_FAILED = 'TEST_NFC_CHIP_FAILED';

export const TEST_OFFLINE_CODE_PENDING = 'TEST_OFFLINE_CODE_PENDING';
export const GOT_OFFLINE_CODE = 'GOT_OFFLINE_CODE';
export const TEST_OFFLINE_CODE_SUCCESS = 'TEST_OFFLINE_CODE_SUCCESS';
export const TEST_OFFLINE_CODE_FAILED = 'TEST_OFFLINE_CODE_FAILED';

export const TEST_AUTO_LOCK_PENDING = 'TEST_AUTO_LOCK_PENDING';
export const TEST_AUTO_LOCK_SUCCESS = 'TEST_AUTO_LOCK_SUCCESS';
export const TEST_AUTO_LOCK_FAILED = 'TEST_AUTO_LOCK_FAILED';

export const UPLOAD_SERIAL_N0_PENDING = 'UPLOAD_SERIAL_N0_PENDING';
export const UPLOAD_SERIAL_N0_SUCCESS = 'UPLOAD_SERIAL_N0_SUCCESS';
export const UPLOAD_SERIAL_N0_FAILED = 'UPLOAD_SERIAL_N0_FAILED';

export const END_TEST = 'END_TEST';
export const CLEAR_TEST = 'CLEAR_TEST';
