//auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

//locks
export const UPDATE_LOCK = 'UPDATE_LOCK';
export const CLEAR_LOCKS = 'CLEAR_LOCKS';

export const SET_RSSI_FILTER = 'SET_RSSI_FILTER';
export const SET_THRESHOLD = 'SET_THRESHOLD';

export const GET_MAX_SERIAL_NUM_REQUEST = 'GET_MAX_SERIAL_NUM_REQUEST';
export const GET_MAX_SERIAL_NUM_SUCCESS = 'GET_MAX_SERIAL_NUM_SUCCESS';
export const GET_MAX_SERIAL_NUM_FAILED = 'GET_MAX_SERIAL_NUM_FAILED';
